services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: root
      database__connection__database: ghost
      url: http://localhost:2368
    volumes:
      - ghost_data:/var/lib/ghost/content
    networks:
      - tt
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tt
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - tt
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  ghost_data:
  mysql_data:

networks:
  tt:
    external: true
