services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./targets:/etc/prometheus/targets
    networks:
      - tt
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - tt
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  prometheus_data:
  grafana_data:

networks:
  tt:
    external: true