global:
  scrape_interval: 15s # Intervalle de collecte des métriques

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9090"]
    # Pour surveiller les services Docker Swarm, ajoutez des cibles dynamiques:
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.yml
